server {
    listen 80;
    server_name dragophynix.local 192.168.29.149;
    
    include /etc/nginx/conf.d/projects/*.conf;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
