server {
    listen 80;
    server_name dragophynix.local 192.168.29.149;

    # This magic line tells Nginx to "insert" all your project snippets here
    include /etc/nginx/conf.d/projects/*.conf;
}
